 -- creo la base de datos
CREATE SCHEMA registro;
 -- usamos la bd
 USE registro;
  -- creo la tabla
  CREATE TABLE usuarios (
	id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
	email VARCHAR(500) NOT NULL,
    contrasenia VARCHAR(500) NOT NULL,
    fecha DATE NOT NULL,
    dni INT NOT NULL,
    foto_de_perfil TEXT NOT NULL,
    createAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updateAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleteAt TIMESTAMP NULL ON UPDATE CURRENT_TIMESTAMP
    
  );
  
  CREATE TABLE productos (
	id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    usuario_id INT NOT NULL,  -- clave foranea
    nombre_producto VARCHAR(500) NOT NULL,
    descripcion_producto VARCHAR(500) NOT NULL,
    createAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updateAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleteAt TIMESTAMP NULL ON UPDATE CURRENT_TIMESTAMP,
    
    FOREIGN KEY (usuario_id) REFERENCES usuarios(id)
    
  );
  
  CREATE TABLE comentarios (
	id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
	id_post INT NOT NULL,
    id_usuario INT NOT NULL,
    texto VARCHAR(500) NOT NULL,
    createAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updateAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleteAt TIMESTAMP NULL ON UPDATE CURRENT_TIMESTAMP,
    
    FOREIGN KEY (id_post) REFERENCES productos(id),
    FOREIGN KEY (id_usuario) REFERENCES usuarios(id)
    
  )